### PR TITLE
Add a strawpoll command example

### PR DESCRIPTION
**Pull request by case**
For less technical folks, here's an example `$strawpoll` command they can copy and paste. (command syntax can easily confuse people, e.g. if they see `'-m'` they may not realize the single-quotes aren't needed — this happened on our Discord server recently, so I figured adding an example might be helpful)

Here's a screenshot:

screenshot 2018-01-17 20 07 33

### CODE REVIEW

**Comment by HyperCoder2975** [comment]
That field is for the description. Feel free to edit in an examples column.

**Comment by case** [comment]
Sure thing, screenshot below. If this looks good, I can add more examples so that it'll look better.

screenshot 2018-01-23 15 49 18

**Comment by TobiasFeld22** [comment]
I suggest instead of having a whole extra column added to the site, using a popup like i did in #10

**Comment by HyperCoder2975** [comment]
Added along with other examples.

**Comment by case** [comment]
Apologies for the delay on this, I got behind on stuff. :(

Looks like you got the examples stuff all squared away?

**Pull request closed without merging**
